### ISSUE TITLE
getTags is not defined

### ISSUE THREAD

**Issue by phanirithvij** [exif-heic-js/exif-heic-js#2]
```js
Uncaught ReferenceError: getTags is not defined
    at FileReader.reader.onload ((index):28)
```

The getTags function is not defined anywhere.

**Comment by phanirithvij** [comment]
It was removed in this commit https://github.com/exif-heic-js/exif-heic-js/commit/8dcc10faaa6b6de604ba0e5f1d6a1498360f0672#diff-ec021b9d20c54fb9e7c6ce8e6fa6eb04L1

**Comment by jim-liu** [comment]
Thanks. Fixed.
